//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<OutsourcingCompany> OutsourcingCompany { get; set; }
        public virtual DbSet<CustomerCompnay> CustomerCompnay { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfo { get; set; }
        public virtual DbSet<PushedHistory> PushedHistory { get; set; }
        public virtual DbSet<CustomerOutsourc> CustomerOutsourc { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<DictionaryItem> DictionaryItem { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Requirement> Requirement { get; set; }
        public virtual DbSet<FinancialManagement> FinancialManagement { get; set; }
        public virtual DbSet<ContractManagement> ContractManagement { get; set; }
        public virtual DbSet<PushInterViewTable> PushInterViewTable { get; set; }
        public virtual DbSet<PersonsEntrySet> PersonsEntrySet { get; set; }
        public virtual DbSet<LeaveDetail> LeaveDetail { get; set; }
        public virtual DbSet<PersonSettlement> PersonSettlement { get; set; }
        public virtual DbSet<InvoiceApplication> InvoiceApplication { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual DbSet<CooperativeContract> CooperativeContract { get; set; }
        public virtual DbSet<EmployeeExpatriation> EmployeeExpatriation { get; set; }
        public virtual DbSet<ImageFile> ImageFile { get; set; }
        public virtual DbSet<My__Dictionary> My__Dictionary { get; set; }
        public virtual DbSet<MyCertificate> MyCertificate { get; set; }
        public virtual DbSet<MyElseinfo> MyElseinfo { get; set; }
        public virtual DbSet<MyExpectations> MyExpectations { get; set; }
        public virtual DbSet<MyLanguage> MyLanguage { get; set; }
        public virtual DbSet<MyMajor> MyMajor { get; set; }
        public virtual DbSet<MyPractice> MyPractice { get; set; }
        public virtual DbSet<MyPrize> MyPrize { get; set; }
        public virtual DbSet<MyProject> MyProject { get; set; }
        public virtual DbSet<MyRated> MyRated { get; set; }
        public virtual DbSet<MyRecruit> MyRecruit { get; set; }
        public virtual DbSet<MyScholarship> MyScholarship { get; set; }
        public virtual DbSet<MyTrain> MyTrain { get; set; }
        public virtual DbSet<MyWorkexperience> MyWorkexperience { get; set; }
    }
}
