//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyExpectations
    {
        public int ID { get; set; }
        public int RecruitId { get; set; }
        public string ExpectationsNature { get; set; }
        public string ExpectationsAddress { get; set; }
        public string ExpectationsProfession { get; set; }
        public string ExpectationsIndustries { get; set; }
        public Nullable<int> ExpectationsMoney { get; set; }
        public Nullable<int> WorkStatus { get; set; }
    }
}
