//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyProject
    {
        public int ID { get; set; }
        public Nullable<int> RecruitId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectTime { get; set; }
        public Nullable<int> IfIT { get; set; }
        public string SoftEnvironment { get; set; }
        public string HardwareEnvironment { get; set; }
        public string DevelopTool { get; set; }
        public string ProjectDuty { get; set; }
        public string ProjectDescribe { get; set; }
    }
}
