//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyWorkexperience
    {
        public int ID { get; set; }
        public Nullable<int> RecruitId { get; set; }
        public string CorporateName { get; set; }
        public string IndustriesClassifications { get; set; }
        public string PositionName { get; set; }
        public string WorkTime { get; set; }
        public Nullable<int> PositionMoney { get; set; }
        public string WorkContent { get; set; }
        public Nullable<int> CorporateNature { get; set; }
        public Nullable<int> CorporateSize { get; set; }
    }
}
