//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSettlement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonSettlement()
        {
            this.LeaveDetail = new HashSet<LeaveDetail>();
        }
    
        public string ID { get; set; }
        public int PersonID { get; set; }
        public int CustomerID { get; set; }
        public int OutCompanyID { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public double WorkDays { get; set; }
        public double RealWorkDays { get; set; }
        public double LeaveDays { get; set; }
        public double OvertimeDays { get; set; }
        public double Wages { get; set; }
        public double RealWages { get; set; }
    
        public virtual CustomerCompnay CustomerCompnay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveDetail> LeaveDetail { get; set; }
        public virtual OutsourcingCompany OutsourcingCompany { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
