//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsEntrySet
    {
        public int Id { get; set; }
        public int PersonalInfoId { get; set; }
        public int CustomerCompnayCompnayId { get; set; }
        public int OutsourcingCompanyCompnayId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public short EntryStatus { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public Nullable<int> EntryMoney { get; set; }
    
        public virtual CustomerCompnay CustomerCompnay { get; set; }
        public virtual OutsourcingCompany OutsourcingCompany { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
