//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInfo()
        {
            this.PushInterViewTable = new HashSet<PushInterViewTable>();
            this.PersonsEntrySet = new HashSet<PersonsEntrySet>();
            this.PersonSettlement = new HashSet<PersonSettlement>();
        }
    
        public int PersonalInfoId { get; set; }
        public string OutsourcingCompanyId { get; set; }
        public string PersonName { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string CaredID { get; set; }
        public string Education { get; set; }
        public string GraduationSchool { get; set; }
        public string GraduationDate { get; set; }
        public string Publications { get; set; }
        public string Attachment { get; set; }
        public string Resume { get; set; }
        public Nullable<int> CVStatue { get; set; }
        public Nullable<int> PeopleStatue { get; set; }
        public Nullable<int> IsActivated { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PushStatue { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushInterViewTable> PushInterViewTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonsEntrySet> PersonsEntrySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSettlement> PersonSettlement { get; set; }
    }
}
