//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushInterViewTable
    {
        public string ID { get; set; }
        public Nullable<int> PersonalInfoId { get; set; }
        public Nullable<int> RequirementId { get; set; }
        public string PlushStatute { get; set; }
        public string FeedbackState { get; set; }
        public string InterviewStatus { get; set; }
        public Nullable<System.DateTime> InterviewTime { get; set; }
        public string InterviewResult { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
        public virtual PushInterViewTable PushInterViewTable1 { get; set; }
        public virtual PushInterViewTable PushInterViewTable2 { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
