//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractManagement
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string ContractName { get; set; }
        public string ContractStatus { get; set; }
        public string ContractTypes { get; set; }
        public string ContractPartner { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string PartnerType { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual CustomerCompnay CustomerCompnay { get; set; }
        public virtual CustomerOutsourc CustomerOutsourc { get; set; }
    }
}
