//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCompnay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCompnay()
        {
            this.ContractManagement = new HashSet<ContractManagement>();
            this.PersonsEntrySet = new HashSet<PersonsEntrySet>();
            this.PersonSettlement = new HashSet<PersonSettlement>();
            this.InvoiceApplication = new HashSet<InvoiceApplication>();
            this.CooperativeContract = new HashSet<CooperativeContract>();
            this.EmployeeExpatriation = new HashSet<EmployeeExpatriation>();
        }
    
        public int CompnayId { get; set; }
        public string CompanyUserName { get; set; }
        public string Pwd { get; set; }
        public string Email { get; set; }
        public string CompnayName { get; set; }
        public string EnglishName { get; set; }
        public string LegalRepresentative { get; set; }
        public string LegalTelephone { get; set; }
        public string UnitResponsible { get; set; }
        public string ResponsibleTelephone { get; set; }
        public string Address { get; set; }
        public string EnterpriseNum { get; set; }
        public string Descriptions { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Nature { get; set; }
        public string BusinessCertificate { get; set; }
        public string EnterpriseNum2 { get; set; }
        public string OperatingPeriod { get; set; }
        public string RegistrationAuthority { get; set; }
        public string BusinessScope { get; set; }
        public string Contract { get; set; }
        public string Type { get; set; }
        public Nullable<int> AuditingStatue { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractManagement> ContractManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonsEntrySet> PersonsEntrySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSettlement> PersonSettlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceApplication> InvoiceApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CooperativeContract> CooperativeContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeExpatriation> EmployeeExpatriation { get; set; }
    }
}
