//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialManagement
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string BothEnds { get; set; }
        public string Money { get; set; }
        public string EntryAndExit { get; set; }
        public Nullable<System.DateTime> ExchangeHour { get; set; }
        public string InvoiceStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string Detail { get; set; }
        public string InvoiceType { get; set; }
    }
}
