//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public string InvoiceID { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<decimal> InvoiceMoney { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerTel { get; set; }
        public string BuyerTaxpayerNumber { get; set; }
        public string BuyerBankDeposit { get; set; }
        public string BuyerBankAccount { get; set; }
        public string SalesName { get; set; }
        public string SalesAddress { get; set; }
        public string SalesTel { get; set; }
        public string SalesTaxpayerNumber { get; set; }
        public string SalesBankDeposit { get; set; }
        public string SalesBankAccount { get; set; }
    }
}
