//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDetail
    {
        public string ID { get; set; }
        public string PersonSettlementID { get; set; }
        public int LeaveType { get; set; }
        public Nullable<decimal> LeaveMoney { get; set; }
        public System.DateTime LeaveStartDate { get; set; }
        public System.DateTime LeaveEndDate { get; set; }
        public Nullable<decimal> LeaveHours { get; set; }
        public string LeaveReason { get; set; }
        public string LeaveBack { get; set; }
    
        public virtual PersonSettlement PersonSettlement { get; set; }
    }
}
