//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPrize
    {
        public int ID { get; set; }
        public Nullable<int> RecruitId { get; set; }
        public string GetPrize { get; set; }
        public Nullable<int> GetYear { get; set; }
        public Nullable<int> GetMonth { get; set; }
        public string Describe { get; set; }
    }
}
