//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRecruit
    {
        public int ID { get; set; }
        public Nullable<int> LoginId { get; set; }
        public string RecruitName { get; set; }
        public string UserName { get; set; }
        public string UserSex { get; set; }
        public string Birthday { get; set; }
        public string TelPhone { get; set; }
        public string Mail { get; set; }
        public string AttendYear { get; set; }
        public string RegisteredPerson { get; set; }
        public string NowAdress { get; set; }
        public string IfMarried { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> CredentialsStatus { get; set; }
        public string CredentialsNumber { get; set; }
        public string OverseasStudent { get; set; }
        public string PoliticsStatus { get; set; }
        public string Private { get; set; }
        public string UpdateTime { get; set; }
        public string CreateTime { get; set; }
    }
}
