//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushedHistory
    {
        public int PushedHistoryId { get; set; }
        public string RequirementId { get; set; }
        public string CustomerCompnayId { get; set; }
        public string PersonalInfoId { get; set; }
        public string OutsourcingCompanyId { get; set; }
        public Nullable<System.DateTime> PushDate { get; set; }
        public string Mark { get; set; }
        public string CustomFeedback { get; set; }
        public string CustPeopleMark { get; set; }
        public Nullable<int> CustPeopleStatue { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
