//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.PushInterViewTable = new HashSet<PushInterViewTable>();
        }
    
        public int RequirementId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string JobName { get; set; }
        public int CompnayId { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string ProjectAddress { get; set; }
        public Nullable<int> Property { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> RecNumber { get; set; }
        public string JobDescription { get; set; }
        public string ComProfile { get; set; }
        public Nullable<int> JobCategory { get; set; }
        public string ComAddress { get; set; }
        public Nullable<int> TecLanguage { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushInterViewTable> PushInterViewTable { get; set; }
    }
}
